import './globals.css';
import { Inter } from 'next/font/google';
import Sidebar from './components/sidebar/sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'PetsPaw',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ display: 'flex' }}>
        <Sidebar />
        <div style={{marginLeft: 'auto', flexGrow: 'grow'}}>{children}</div>
      </body>
    </html>
  );
}
