import './globals.css';
import { Jost } from 'next/font/google';
import Sidebar from './components/sidebar/sidebar';
import { Providers } from './components/providers/providers';
import css from './layout.module.css';

const jost = Jost({ subsets: ['latin'] });

export const metadata = {
  title: 'PetsPaw',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <Providers>
        <body className={jost.className} style={{ display: "block" }}>
          <main className={css.main}>
            <div className={css.sidebar}><Sidebar /></div>            
            <div className={css.children}>{children}</div>
          </main>
        </body>
      </Providers>
    </html>
  );
}
